//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSILid4Exe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSILid4Exe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rem call %1
        ///call notepad.exe MSILid4Exe.log.
        /// </summary>
        internal static string CMD {
            get {
                return ResourceManager.GetString("CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] template {
            get {
                object obj = ResourceManager.GetObject("template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Config&gt;  
        ///  
        ///  &lt;FileName&gt;%CD%\*.exe&lt;/FileName&gt;
        ///  &lt;FileRegex&gt;^(?&amp;lt;FileName&amp;gt;(?!MSILid4Exe).*\.exe)$&lt;/FileRegex&gt;  
        ///  &lt;CmdArgs&gt;/default&lt;/CmdArgs&gt;  
        ///  &lt;SelectFile&gt;1&lt;/SelectFile&gt;
        ///  
        ///  &lt;SummaryInfo&gt;
        ///	  &lt;Property name=&quot;Author&quot;&gt;$FILE_COMPANY$&lt;/Property&gt;
        ///	  &lt;Property name=&quot;Comments&quot;&gt;artem.karimov@weadmire.io&lt;/Property&gt;
        ///	  &lt;Property name=&quot;Keywords&quot;&gt;$PRODUCT_NAME$ Setup Installer&lt;/Property&gt;
        ///	  &lt;Property name=&quot;LastSavedBy&quot;&gt;MSILid4Exe&lt;/Property&gt;
        ///	  &lt;Property name= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
